### ISSUE TITLE
LazyScrollView

### ISSUE THREAD

**Issue by huangboju** [HistoryZhang/LazyScrollView#1]
https://github.com/chenjunpu/LazyScrollView 这里也有一个
我想把这个翻成swift的，不知道你们哪个好，他的有内存泄露，你的代码更简单些

**Comment by KelvinQQ** [comment]
他的代码并没有真正实现复用吧，简单了看了下，就是那个`hidden`有问题；然后二分法好像也没有做，不过对于少量数据影响到也不大。不过既然是使用人家的思想，就应该用到极致。
其实了解了思路，翻译成`swift`应该不是很难的事，重要的还是理解原文的思想吧。

**Comment by huangboju** [comment]
3q。
